[2025-02-05T11:56:26.961+0530] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-05T11:56:26.968+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: brewery_data_pipeline.fetch_store_brewery_data manual__2025-02-05T06:21:21+00:00 [queued]>
[2025-02-05T11:56:26.972+0530] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: brewery_data_pipeline.fetch_store_brewery_data manual__2025-02-05T06:21:21+00:00 [queued]>
[2025-02-05T11:56:26.973+0530] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-02-05T11:56:26.987+0530] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_store_brewery_data> on 2025-02-05 06:21:21+00:00
[2025-02-05T11:56:26.997+0530] {standard_task_runner.py:72} INFO - Started process 272949 to run task
[2025-02-05T11:56:27.001+0530] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'brewery_data_pipeline', 'fetch_store_brewery_data', 'manual__2025-02-05T06:21:21+00:00', '--job-id', '37', '--raw', '--subdir', 'DAGS_FOLDER/pipeline_miniproject.py', '--cfg-path', '/tmp/tmp7mmt8luo']
[2025-02-05T11:56:27.002+0530] {standard_task_runner.py:105} INFO - Job 37: Subtask fetch_store_brewery_data
[2025-02-05T11:56:27.051+0530] {task_command.py:467} INFO - Running <TaskInstance: brewery_data_pipeline.fetch_store_brewery_data manual__2025-02-05T06:21:21+00:00 [running]> on host umang-Latitude-7490
[2025-02-05T11:56:27.097+0530] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='brewery_data_pipeline' AIRFLOW_CTX_TASK_ID='fetch_store_brewery_data' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T06:21:21+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T06:21:21+00:00'
[2025-02-05T11:56:27.098+0530] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-02-05T11:56:27.098+0530] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-02-05T11:56:27.099+0530] {logging_mixin.py:190} INFO - Current task name:fetch_store_brewery_data state:running start_date:2025-02-05 06:26:26.968821+00:00
[2025-02-05T11:56:27.099+0530] {logging_mixin.py:190} INFO - Dag name:brewery_data_pipeline and current dag run status:running
[2025-02-05T11:56:27.099+0530] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-05T11:56:27.695+0530] {__init__.py:149} INFO - package: mysql.connector.plugins
[2025-02-05T11:56:27.695+0530] {__init__.py:150} INFO - plugin_name: caching_sha2_password
[2025-02-05T11:56:27.695+0530] {__init__.py:154} INFO - AUTHENTICATION_PLUGIN_CLASS: MySQLCachingSHA2PasswordAuthPlugin
[2025-02-05T11:56:27.702+0530] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/airflow/dags/pipeline_miniproject.py", line 95, in fetch_and_store_data
    cursor.execute(insert_query, (
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/cursor.py", line 416, in execute
    self._connection.cmd_query(
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 106, in wrapper
    result = method(cnx, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/utils.py", line 742, in handle_cnx_method
    raise err
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/utils.py", line 738, in handle_cnx_method
    return cnx_method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/connection.py", line 937, in cmd_query
    result = self._handle_result(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/utils.py", line 742, in handle_cnx_method
    raise err
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/utils.py", line 738, in handle_cnx_method
    return cnx_method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/connection.py", line 703, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'state' in 'field list'
[2025-02-05T11:56:27.707+0530] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-02-05T11:56:27.707+0530] {logging_mixin.py:190} INFO - Task start:2025-02-05 06:26:26.968821+00:00 end:2025-02-05 06:26:27.706927+00:00 duration:0.738106
[2025-02-05T11:56:27.707+0530] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_store_brewery_data> dag:<DAG: brewery_data_pipeline> dagrun:<DagRun brewery_data_pipeline @ 2025-02-05 06:21:21+00:00: manual__2025-02-05T06:21:21+00:00, state:running, queued_at: 2025-02-05 06:21:21.812910+00:00. externally triggered: True>
[2025-02-05T11:56:27.707+0530] {logging_mixin.py:190} INFO - Failure caused by 1054 (42S22): Unknown column 'state' in 'field list'
[2025-02-05T11:56:27.707+0530] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=brewery_data_pipeline, task_id=fetch_store_brewery_data, run_id=manual__2025-02-05T06:21:21+00:00, execution_date=20250205T062121, start_date=20250205T062626, end_date=20250205T062627
[2025-02-05T11:56:27.718+0530] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-05T11:56:27.719+0530] {standard_task_runner.py:124} ERROR - Failed to execute job 37 for task fetch_store_brewery_data (1054 (42S22): Unknown column 'state' in 'field list'; 272949)
Traceback (most recent call last):
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/airflow/dags/pipeline_miniproject.py", line 95, in fetch_and_store_data
    cursor.execute(insert_query, (
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/cursor.py", line 416, in execute
    self._connection.cmd_query(
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/opentelemetry/context_propagation.py", line 106, in wrapper
    result = method(cnx, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/utils.py", line 742, in handle_cnx_method
    raise err
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/utils.py", line 738, in handle_cnx_method
    return cnx_method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/connection.py", line 937, in cmd_query
    result = self._handle_result(
             ^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/utils.py", line 742, in handle_cnx_method
    raise err
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/utils.py", line 738, in handle_cnx_method
    return cnx_method(cnx, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/umang/Dataslush_umang/airflow_env/lib/python3.12/site-packages/mysql/connector/connection.py", line 703, in _handle_result
    raise get_exception(packet)
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'state' in 'field list'
[2025-02-05T11:56:27.737+0530] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-02-05T11:56:27.746+0530] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T11:56:27.747+0530] {local_task_job_runner.py:245} INFO - ::endgroup::
