[2025-01-28T10:13:05.028+0000] {processor.py:186} INFO - Started process (PID=14800) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:13:05.031+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:13:05.037+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:13:05.035+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:13:05.080+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:13:05.069+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:13:05.083+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:13:05.081+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:13:05.085+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:13:05.099+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.091 seconds
[2025-01-28T10:15:25.689+0000] {processor.py:186} INFO - Started process (PID=14992) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:15:25.695+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:15:25.702+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:15:25.699+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:15:25.728+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:15:25.723+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:15:25.730+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:15:25.729+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:15:25.731+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:15:25.742+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.072 seconds
[2025-01-28T10:17:06.684+0000] {processor.py:186} INFO - Started process (PID=15181) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:17:06.688+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:17:06.696+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:17:06.693+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:17:06.743+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:17:06.735+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:17:06.746+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:17:06.744+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:17:06.747+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:17:06.758+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.112 seconds
[2025-01-28T10:19:27.953+0000] {processor.py:186} INFO - Started process (PID=15410) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:19:27.957+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:19:27.964+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:19:27.961+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:19:28.055+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:19:28.033+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:19:28.061+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:19:28.058+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:19:28.065+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:19:28.097+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.173 seconds
[2025-01-28T10:21:12.788+0000] {processor.py:186} INFO - Started process (PID=15574) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:21:12.791+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:21:12.798+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:21:12.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:21:12.841+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:21:12.833+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:21:12.843+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:21:12.842+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:21:12.844+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:21:12.859+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
[2025-01-28T10:23:04.415+0000] {processor.py:186} INFO - Started process (PID=15701) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:23:04.418+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:23:04.423+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:23:04.422+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:22:34.370+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:22:34.360+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:22:34.373+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:22:34.371+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:22:34.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:22:34.390+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2025-01-28T10:24:17.975+0000] {processor.py:186} INFO - Started process (PID=15868) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:24:18.086+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:24:18.101+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:24:18.096+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:24:18.220+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:24:18.201+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:24:18.226+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:24:18.223+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:24:18.229+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:24:18.263+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.322 seconds
[2025-01-28T10:25:58.406+0000] {processor.py:186} INFO - Started process (PID=16102) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:25:58.411+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:25:58.422+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:25:58.419+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:25:58.560+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:25:58.531+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:25:58.568+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:25:58.564+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:25:58.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:25:58.617+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.258 seconds
[2025-01-28T10:28:43.449+0000] {processor.py:186} INFO - Started process (PID=16324) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:28:43.453+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:28:43.462+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:28:43.459+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:28:43.545+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:28:43.527+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:28:43.551+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:28:43.548+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:28:43.554+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:28:43.572+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.162 seconds
[2025-01-28T10:31:13.826+0000] {processor.py:186} INFO - Started process (PID=16520) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:31:13.833+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:31:13.848+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:31:13.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:31:13.969+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:31:13.951+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:31:13.974+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:31:13.972+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:31:13.976+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:31:13.994+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.235 seconds
[2025-01-28T10:33:39.381+0000] {processor.py:186} INFO - Started process (PID=16750) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:33:39.384+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:33:39.391+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:33:39.389+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:33:39.444+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:33:39.435+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:33:39.447+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:33:39.446+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:33:39.448+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:33:39.462+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2025-01-28T10:36:18.723+0000] {processor.py:186} INFO - Started process (PID=16990) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:36:18.731+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:36:18.747+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:36:18.742+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:36:18.884+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:36:18.860+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:36:18.891+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:36:18.887+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:36:18.895+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:36:18.939+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.284 seconds
[2025-01-28T10:39:15.137+0000] {processor.py:186} INFO - Started process (PID=17269) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:39:15.145+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:39:15.161+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:39:15.156+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:39:15.284+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:39:15.266+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:39:15.290+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:39:15.287+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:39:15.293+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:39:15.317+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.249 seconds
[2025-01-28T10:40:43.579+0000] {processor.py:186} INFO - Started process (PID=17368) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:40:43.583+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:40:43.590+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:40:43.588+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:40:43.634+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:40:43.627+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:40:43.636+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:40:43.635+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:40:43.637+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:40:43.651+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2025-01-28T10:42:22.090+0000] {processor.py:186} INFO - Started process (PID=17574) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:42:22.094+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:42:22.103+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:42:22.100+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:42:22.149+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:42:22.142+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:42:22.151+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:42:22.150+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:42:22.152+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:42:22.163+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2025-01-28T10:46:10.128+0000] {processor.py:186} INFO - Started process (PID=17909) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:46:10.215+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:46:10.222+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:46:10.219+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:46:10.257+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:46:10.250+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:46:10.259+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:46:10.258+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:46:10.260+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:46:10.274+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.183 seconds
[2025-01-28T10:47:44.233+0000] {processor.py:186} INFO - Started process (PID=18028) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:47:44.236+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:47:44.243+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:47:44.242+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:47:44.289+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:47:44.280+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:47:44.292+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:47:44.291+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:47:44.294+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:47:44.311+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2025-01-28T10:49:06.495+0000] {processor.py:186} INFO - Started process (PID=18214) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:49:06.498+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:49:06.504+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:49:06.502+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:49:06.557+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:49:06.545+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:49:06.560+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:49:06.559+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:49:06.562+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:49:06.581+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2025-01-28T10:50:47.169+0000] {processor.py:186} INFO - Started process (PID=18316) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:50:47.172+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:50:47.178+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:50:47.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:50:47.217+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:50:47.210+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:50:47.220+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:50:47.219+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:50:47.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:50:47.236+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.092 seconds
[2025-01-28T10:52:27.429+0000] {processor.py:186} INFO - Started process (PID=18569) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:52:27.432+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:52:27.439+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:52:27.438+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:52:27.486+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:52:27.476+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:52:27.489+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:52:27.487+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:52:27.491+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:52:27.510+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.108 seconds
[2025-01-28T10:53:38.208+0000] {processor.py:186} INFO - Started process (PID=18731) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:53:38.427+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:53:38.435+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:53:38.432+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:53:38.486+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:53:38.476+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:53:38.490+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:53:38.488+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:53:38.492+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:53:38.510+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.328 seconds
[2025-01-28T10:55:00.895+0000] {processor.py:186} INFO - Started process (PID=18845) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:55:00.898+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:55:00.904+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:55:00.902+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:55:00.947+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:55:00.939+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:55:00.950+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:55:00.948+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:55:00.951+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:55:00.967+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2025-01-28T10:56:29.250+0000] {processor.py:186} INFO - Started process (PID=19051) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:56:29.253+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:56:29.258+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:56:29.257+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:56:29.309+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:56:29.299+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:56:29.312+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:56:29.310+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:56:29.313+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:56:29.330+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2025-01-28T10:58:01.744+0000] {processor.py:186} INFO - Started process (PID=19207) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:58:01.747+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:58:01.753+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:58:01.751+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:58:01.803+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:58:01.793+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:58:01.806+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:58:01.804+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:58:01.807+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:58:01.823+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2025-01-28T10:59:30.023+0000] {processor.py:186} INFO - Started process (PID=19392) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:59:30.038+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T10:59:30.044+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:59:30.043+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:59:30.087+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:59:30.078+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T10:59:30.090+0000] {logging_mixin.py:190} INFO - [2025-01-28T10:59:30.088+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T10:59:30.092+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T10:59:30.112+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2025-01-28T11:01:24.693+0000] {processor.py:186} INFO - Started process (PID=19580) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:01:24.748+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:01:24.756+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:01:24.754+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:01:24.812+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:01:24.801+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:01:24.816+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:01:24.815+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:01:24.818+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:01:24.842+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.174 seconds
[2025-01-28T11:02:43.808+0000] {processor.py:186} INFO - Started process (PID=19652) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:02:44.291+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:02:44.314+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:02:44.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:02:44.371+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:02:44.361+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:02:44.375+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:02:44.373+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:02:44.376+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:02:44.396+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.611 seconds
[2025-01-28T11:04:16.083+0000] {processor.py:186} INFO - Started process (PID=19876) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:04:16.086+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:04:16.091+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:04:16.090+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:04:16.133+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:04:16.122+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:04:16.136+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:04:16.134+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:04:16.137+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:04:16.152+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2025-01-28T11:05:57.900+0000] {processor.py:186} INFO - Started process (PID=20002) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:05:57.965+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:05:57.980+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:05:57.976+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:05:58.064+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:05:58.047+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:05:58.068+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:05:58.066+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:05:58.070+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:05:58.084+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.207 seconds
[2025-01-28T11:07:58.512+0000] {processor.py:186} INFO - Started process (PID=20171) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:07:58.515+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:07:58.522+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:07:58.520+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:07:58.568+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:07:58.558+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:07:58.571+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:07:58.570+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:07:58.573+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:07:58.592+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2025-01-28T11:10:03.836+0000] {processor.py:186} INFO - Started process (PID=20375) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:10:03.839+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:10:03.846+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:10:03.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:10:03.896+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:10:03.887+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:10:03.899+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:10:03.897+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:10:03.900+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:10:03.918+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2025-01-28T11:12:24.450+0000] {processor.py:186} INFO - Started process (PID=20563) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:12:24.453+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:12:24.460+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:12:24.458+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:12:24.508+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:12:24.497+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:12:24.511+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:12:24.509+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:12:24.513+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:12:24.537+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.114 seconds
[2025-01-28T11:13:35.049+0000] {processor.py:186} INFO - Started process (PID=20678) to work on /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:13:35.166+0000] {processor.py:914} INFO - Processing file /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2025-01-28T11:13:35.172+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:13:35.170+0000] {dagbag.py:588} INFO - Filling up the DagBag from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:13:35.217+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:13:35.209+0000] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2025-01-28T11:13:35.220+0000] {logging_mixin.py:190} INFO - [2025-01-28T11:13:35.219+0000] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2025-01-28T11:13:35.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2025-01-28T11:13:35.236+0000] {processor.py:208} INFO - Processing /mnt/c/Users/Admin/Desktop/ud_data/Dataslush_umang/airflow/airflow_venv/lib/python3.12/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.207 seconds
